# Generated by Django 3.2.5 on 2021-07-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Email_address',
        ),
        migrations.AddField(
            model_name='student',
            name='Email_address',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Email_address',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
    ]
