# Generated by Django 3.2.5 on 2021-07-05 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_class_class_metarials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.CharField(max_length=45, null=True)),
                ('Written', models.TextField(null=True)),
                ('Voice', models.BooleanField(null=True)),
                ('Class_Metarials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.class_metarials')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.student')),
            ],
        ),
    ]
