# Generated by Django 3.2.5 on 2021-07-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='Student',
        ),
        migrations.AddField(
            model_name='class',
            name='Student',
            field=models.ManyToManyField(to='portfolio.Student'),
        ),
    ]
