# Generated by Django 3.2.5 on 2021-07-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20210706_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='upload/'),
        ),
    ]
