# Generated by Django 3.2.5 on 2021-07-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='Class_name',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
